name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Prod
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:latest

  unit_test:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: |
          echo "Needs implement unit tests"

  regression_test:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: |
          echo "Needs implement regression tests"
  deploy:
    needs:
      - unit_test
      - regression_test
    runs-on: davo-runner
    steps:
      - name: Deploy to Production (Main)
        if: github.ref_name == 'main'
        run: |
          docker pull ailabcau/tender-api:latest
          docker service update --force --with-registry-auth --detach=false --image ailabcau/tender-api:latest tender_api
          docker container prune -f
